In [3]:
import numpy as np

arr = np.array([7,2,9,1,0,11,26])
print(np.partition(arr, -4))
print(np.partition(arr, 4))
print(np.partition(arr, -2))
print(np.partition(arr, 2))

[ 2  1  0  7  9 11 26]
[ 2  1  0  7  9 11 26]
[ 2  1  0  7  9 11 26]
[ 0  1  2  9  7 11 26]


In [7]:
from scipy.stats import randint

randint(low=1, high=10)

In [11]:
print(np.random.randint(0, 10, 5))

[1 9 8 9 9]
